#!/store/EQUIPES/AMIG/MEMBERS/diego.zea/bin/julia19

#=
#SBATCH --nodelist=node48
#SBATCH --time=900:00:00
#SBATCH --mem=100G
#SBATCH --cpus-per-task=10
#SBATCH --gpus=1
#SBATCH --output=BioEmu-%j.out
=#
import Pkg
Pkg.activate("/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/scripts/update")
cd("/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/data/test_set/")

# Load necessary packages 
using DataFrames, CSV
import MIToS
using MIToS.MSA
using MIToS.PDB
using Dates
using Glob
using AlphaConformers
using Plots

################################### MAIN ######################################################
"""
This script runs BioEmu on a set of PDB files, generating conformers and calculating RMSD values against both holo and apo structures.
The results are saved in a folder 
Then are analyse in a CSV file and visualized with scatter plots.

Input:
-PDB_FOLDER: Path to the folder containing PDB files.
-ENV["BIOEMU_COLABFOLD_DIR"]: Path to the BioEmu environment.
-micromamba_path: Path to the micromamba executable.
-env_path: Path to the BioEmu environment.
-file_path: Path to the CSV file containing PDB information. file output by test_set_development.jl
-folder_path: Path to the folder where results will be saved and where are apo and holo PDB files.
Output
- A folder for each PDB file containing the results of BioEmu.
- A CSV file with RMSD results for each model generated by BioEmu.
- A scatter plot visualizing the RMSD results.

Need to have the script BIOEMU.py 
Need to select inthe code if we use the PDB file or the MSA file to run BioEmu.
If you use the MSA file, you need to have the MSA file output by AlphaConformers.jl.
Be careful to the path access needded in the code
"""

########################## Information to fill #################################
# Path to the PDB folder
const PDB_FOLDER = "/alpha/database/pdb/pdb_files"
# Path to the environment for BioEmu
ENV["BIOEMU_COLABFOLD_DIR"] = "/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/scripts/update/bioemu_colabfold_env"
#micromamba path and environment path
micromamba_path = "/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/scripts/update/micromamba/micromamba"
env_path = "/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/scripts/update/mamba_envs/python310"
#Path to the information file 
file_path="info_test_set.csv" # File output py test_set_development.jl
# Path to the folder where the results will be saved and where are apo and holo PDB files
folder_path ="/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/data/test_set/"

######################################################################################
@show "Date de début ", Dates.format(now(), "HH:MM:SS")
# Load the information file
dev_set=DataFrames.DataFrame(CSV.File(file_path,
comment="#", missingstring=["", "None"])) 

#For each row in the DataFrame, process the PDB file
for row in eachrow(dev_set)
    # Get the PDB identifier and chain
    apo = row.PDB_apo
    chain= row.CHAIN_apo
    #apo_model=row.INDEX_apo

    @info "Processing file: $apo"

    #output path for the results
    output_path = joinpath(folder_path, apo*"_BIOEMU_MSA")
    if !isdir(output_path)
        mkdir(output_path)
    end
    
    #Get apo PDB file
    path_file=joinpath( apo*"_"*chain*".pdb")
    if !isfile(path_file)
        MIToS.PDB.downloadpdb(String(apo); format=MIToS.PDB.PDBFile, filename=path_file)
    end
    
    #################### BioEmu with a PDB file ######################
    #=
    #Read the PDB file
    pdb_file = MIToS.PDB.read_file(path_file, MIToS.PDB.PDBFile)
    if pdb_file === nothing
        @warn "PDB file is empty or could not be read: $path_file"
        continue
    end
    # Get the sequence from the PDB file
    sequences=MIToS.PDB.modelled_sequences(pdb_file)
    @show sequences
    seq = first(values(sequences))       
    @show seq

    #Run BioEmu 
    run(`$micromamba_path run -p $env_path python3 -m bioemu.sample --sequence $seq --num_samples 4000 --output_dir $output_path`)

    =#
    ################################################################

    ################## BioEmu with a MSA file ########################
    # Get the MSA file path
    msa_path = joinpath(folder_path, apo*"_AlphaConformer","sequence.a3m")

    # Run BioEmu with a MSA file
    run(`$micromamba_path run -p $env_path python3 -m bioemu.sample --sequence $msa_path --num_samples 4000 --output_dir $output_path`)
    ################################################################

    @show output_path
    while true
        if isfile(joinpath(output_path,"samples.xtc"))
            break
        end
        @info "Waiting for the output file to be created..."
        sleep(60)  # Wait until the file is created
    end
    #move the output files to the output path
    pdb_output_path = joinpath(output_path, "PDB_result")
    if isdir(pdb_output_path)
        rm(pdb_output_path; force=true, recursive=true)
    end
    mkdir(pdb_output_path)
    cd("/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/scripts/")

    #Run code to extract the predicted structures
    run(`$micromamba_path run -p $env_path python3 BIOEMU.py --pdb_file $output_path`)

    cd("/store/EQUIPES/AMIG/MEMBERS/julie.daniel/AlphaConformers.jl/data/test_set/")

    #### Create the plot
    # Get the model files generated by BioEmu
    model_files=Glob.glob("frame_*.pdb",output_path*"/PDB_result/")
    println(length(model_files))
    println(typeof(model_files))

    results = DataFrame(Model=String[], RMSD_Holo=Float64[], RMSD_Apo=Float64[])
    # For each model file, calculate the RMSD against the holo and apo structures
    for model in model_files
        println(model)
        holo = row.PDB_holo
        chain= row.CHAIN_holo
        #holo_model=row.INDEX_holo
        structure_model = read_file(model, PDBFile,group="ATOM")
        structure_apo = read_file(path_file, PDBFile,group="ATOM")
        structure_holo = read_file(joinpath(holo*"_"*chain*".pdb"), PDBFile,group="ATOM")

        _,_,_,rmsd_holo,coverage,_=AlphaConformers.structural_alignment(structure_model, structure_holo)
        _,_,_,rmsd_apo,coverage,_ =AlphaConformers.structural_alignment(structure_model, structure_apo)
        println(basename(model))
        push!(results, (basename(model), rmsd_holo, rmsd_apo))
        
    end
    # Save the results to a CSV file
    CSV.write(output_path*"/rmsd_results_"*apo*".csv", results)
    #Visualisation of the result 
    scatter(
        results.RMSD_Apo,
        results.RMSD_Holo,
        xlabel = "Apo",
        ylabel = "Holo",
        title = "$apo with BioEmu",
        marker = :circle,
        legend = false,
        xlims = (0, 30),
        ylims = (0, 30)
    )

    # Création de l'inset (zoom sur 0–7)
    scatter!(
        results.RMSD_Apo,
        results.RMSD_Holo,
        xlims = (0, 7),
        ylims = (0, 7),
        inset = (1, bbox(0.05, 0.05, 0.5, 0.5, :bottom, :right)),
        subplot = 2,
        marker = :circle,
        markersize = 3,  
        legend = false,
        xlabel = "",
        ylabel = "",
        title = "Zoom"
    )

    savefig(output_path*"/rmsd_scatter_"*apo*".png")  # Sauvegarde du plot

    
end

@show "Date de fin ", Dates.format(now(), "HH:MM:SS")
@show "End"

################################################# END #####################################################