# Progress bar -------------------------------- #
mutable struct Progress
    steps::Vector{String}   # ← Vector{String}, pas String
    current::Int
    total::Int
end

"""
    progress_bar(progress, step_name)

Print and advance the text progress bar used by the main pipeline.

# Arguments
- `progress`: Mutable progress state.
- `step_name`: Name of the pipeline step that just completed.

# Returns
`nothing`.
"""
function progress_bar(p::Progress, step_name::String)
    p.current += 1
    pct = round(Int, 100 * p.current / p.total)
    filled = round(Int, 40 * p.current / p.total)
    bar = "█" ^ filled * "░" ^ (40 - filled)
    println("\n[$(p.current)/$(p.total)] $step_name")
    println("[$bar] $pct%")
    flush(stdout)
end

# Structure distance -------------------------------- #
function _aligned_pdb_file(query, target, aligned_structures_folder)
    file_name = "aln_$(query)_$(target).pdb"
    joinpath(aligned_structures_folder, file_name)
end

function _get_aligned_residues(query, target, paths, tstart, tend)
    # msa = read(paths.msa, MIToS.MSA.FASTA)
    pdb_file = _aligned_pdb_file(query, target, paths)
    res = MIToS.PDB.read_file(pdb_file, MIToS.PDB.PDBFile)
    # NOTE: Foldseek creates a single chain for the aligned structures: A
    # NOTE: tstart and tend are the residue numbers in the Foldseek-aligned structure
    res[tstart:tend]
end

# NOTE: This function only works before adding external structures into the
# Foldseek results, as it relies on the structures generated by Foldseek.
function _get_aligned_structures(foldseek_results::DataFrames.DataFrame)
    structures = OrderedCollections.OrderedDict{String,Vector{MIToS.PDB.PDBResidue}}()
    for row in eachrow(foldseek_results)
        paths = _get_paths(row.file)
        try
            structures[row.target] = _get_aligned_residues(
                row.query,
                row.target,
                paths.structures,
                row.tstart,
                row.tend,
            )
        catch err
            @error "Error ($err) getting structures from row: $row"
            continue
        end
    end
    structures
end

# Sequence alignment --------------------------------------- #

"""
    get_res_beg_end(pdb_file) -> (first_residue, last_residue)

Return the minimum and maximum numeric residue ids found in ATOM records.

# Arguments
- `pdb_file`: Path to a PDB file.

# Returns
A tuple with the first and last residue numbers found in the file.
"""
function get_res_beg_end(pdb_file::String)
    res_ids = Int[]

    open(pdb_file, "r") do io
        for line in eachline(io)
            if startswith(line, "ATOM")
                raw = strip(line[23:26])

                # Keep only the digits.
                num = match(r"\d+", raw)

                if num !== nothing
                    push!(res_ids, parse(Int, num.match))
                end
            end
        end
    end

    return minimum(res_ids), maximum(res_ids)
end

"""
    vector_to_msa(seqs) -> MSA

Create a temporary FASTA file from sequences and read it as an MSA.

# Arguments
- `seqs`: Vector of ungapped or aligned sequence strings.

# Returns
An MSA object with generated sequence names `seq_1`, `seq_2`, and so on.
"""
function vector_to_msa(seqs::Vector{String})
    names = ["seq_$(i)" for i = 1:length(seqs)]

    tmpfile = tempname() * ".fasta"

    open(tmpfile, "w") do io
        for (name, seq) in zip(names, seqs)
            println(io, ">$name")
            println(io, seq)
        end
    end

    msa = read(tmpfile, FASTA)

    return msa
end

"""
    align_full_seq(full_seq, msa) -> Vector{String}

Project an existing MSA onto a supplied full reference sequence.

# Arguments
- `full_seq`: Full query sequence to use as the new reference row.
- `msa`: Sequence vector where the first entry is the current query/reference.

# Returns
A vector of aligned sequence strings. Positions absent from the original reference are
filled with gaps in the non-query sequences.
"""
function align_full_seq(full_seq, msa)

    ref_seq = msa[1]  # The first MSA sequence is the reference.
    @show ref_seq
    @show full_seq
    mapping = Int[]  # Positions in ref_seq, or 0 for gaps.

    i = 1  # index ref_seq

    for c in full_seq
        if i <= length(ref_seq) && c == ref_seq[i]
            push!(mapping, i)
            i += 1
        else
            push!(mapping, 0)  # gap
        end
    end
    @show mapping
    # Build the new MSA.
    new_msa = String[]

    # First row = full_seq (the clean reference).
    push!(new_msa, full_seq)

    # Other sequences.
    for seq in msa[2:end]
        seq_string=seq
        new_seq = ""
        for pos in mapping
            if pos == 0
                new_seq *= "-"
            else
                new_seq *= seq_string[pos]
            end
        end
        push!(new_msa, new_seq)
    end
    @show length(new_msa)
    return new_msa
end

"""
    alphaconformers(input_pdb, pdb_folder, out_folder; kwargs...)

Run the AlphaConformers pipeline for one query structure.

The function searches for related structures, builds a merged MSA, groups template
structures, and writes one output folder per template cluster.

# Arguments
- `input_pdb`: Query PDB file. The file name must use `PDBCODE_CHAIN.pdb`, for
  example `1EX6_B.pdb`.
- `pdb_folder`: Folder containing local PDB files used when adding known structures.
- `out_folder`: Output folder. It is created by the pipeline if needed.

# Keywords
- `n_threads`: Number of Foldseek threads. Defaults to `Threads.nthreads()`.
- `db`: Foldseek database paths used for the search.
- `evalue_cutoff`: Maximum Foldseek e-value. Set to `NaN` to keep all hits.
- `cutoff`: RMSD cutoff used to group template structures.
- `test_analyse`: Remove other known structures from the query UniProt entry before
  clustering.
- `keep_query`: Keep the query structure when `test_analyse=true`.
- `full_seq`: Optional full query sequence used to write an MSA aligned to the full
  sequence.

# Returns
`nothing`. Results are written under `out_folder`.

# Throws
Throws an error if the query file name does not include a PDB code and chain, or if
no targets remain after optional query-conformation removal.
"""
function alphaconformers(
    input_pdb::String,
    pdb_folder::String,
    out_folder::String;
    n_threads::Int = Threads.nthreads(),
    db::Vector{String} = ["/alpha/database/pdb/fullpdb"],
    evalue_cutoff::Float64 = 1e-5,
    cutoff::Float64 = 1.0,
    test_analyse::Bool = false,
    keep_query::Bool = true,
    full_seq::Union{Missing,String} = missing,
)
    println("----------------------------------------")
    println("AlphaConformers start running...")
    println("----------------------------------------")

    steps = [
        "Foldseek search",
        "Merging tables",
        "Adding known conformations",
        "Merging MSAs",
        "Final MSA",
        "Aligned structures",
        "Clustering Hobohm",
        "Creating folders + cleanup",
    ]
    n_steps = test_analyse ? 8 : 7   # Conditional alignment.
    prog = Progress(steps, 0, n_steps)


    println("Available threads", Threads.nthreads())

    #Get the query pdb code and chain from the input file name
    parts=split(basename(input_pdb), "_")
    if length(parts) < 2
        error(
            "The PDB filename must use the format 'PDBCODE_CHAIN.pdb', for example '1EX6_B.pdb'",
        )
    end
    query_pdb_code = parts[1]
    query_chain_code=String(first(splitext(parts[2])))
    println("Query PDB code: $query_pdb_code, Query chain code: $query_chain_code")

    println("Running Foldseek")
    output = run_foldseek(input_pdb, n_threads, db, out_folder = out_folder)
    progress_bar(prog, "Foldseek search")
    # Init empty vector to store the table files
    output_vector = Vector{String}()
    for item in output
        push!(output_vector, item.table_file)  # Add to the vector.
    end

    # Create the merged table
    merged_table = merge_tables(output_vector)
    println("Size of merged table: $(size(merged_table))")
    if !isnan(evalue_cutoff)
        println("Filtering results with e-value cutoff: $evalue_cutoff")
        filter!(row -> row.evalue < evalue_cutoff, merged_table)
        println("Size of merged table after filtering : $(size(merged_table))")
    end

    if size(merged_table, 1) == 0
        @error "No results found after filtering with e-value cutoff: $evalue_cutoff"
        return
    end
    progress_bar(prog, "Merging tables")
    println("Adding known conformations")

    sifts_uniprot_mapping = get_uniprot_mapping()
    clean_table = add_known_conformations!(
        deepcopy(merged_table),
        sifts_uniprot_mapping,
        pdb_folder,
        out_folder,
        input_pdb,
        n_threads,
    )
    println("Size of all target found : $(size(clean_table))")
    progress_bar(prog, "Adding known conformations")

    if test_analyse
        println(
            "Remove know structure from query uniprot from targets (keep query itself in targets)",
        )
        query_found=filter(
            row ->
                startswith(row.target, uppercase(query_pdb_code)) &&
                endswith(row.target, uppercase(query_chain_code)),
            clean_table,
        )
        if isempty(query_found)
            @warn "The query structure is not in all target found ! "
        end
        expanded_table=delete_query_from_target(
            deepcopy(clean_table),
            sifts_uniprot_mapping,
            String(query_pdb_code),
            String(query_chain_code),
        )
        println("Size of after removing query other conformations: $(size(expanded_table))")
        if keep_query
            println("Keep query in targets")
            expanded_table=vcat(query_found, expanded_table)
            println("Size of expanded table with query: $(size(expanded_table))")
        end
        isempty(expanded_table) &&
            error("No targets remaining after removing query from targets.")
        CSV.write(joinpath(out_folder, "expanded_table_delete.csv"), expanded_table)
    else
        expanded_table=deepcopy(clean_table)
    end

    println("Create merged MSAS")
    merged_msa = merge_msas(expanded_table)
    MIToS.MSA.write_file(
        joinpath(out_folder, "all_sequence.a3m"),
        merged_msa,
        MIToS.MSA.A3M,
    )
    println("Size of merged MSA: $(size(merged_msa))")
    progress_bar(prog, "Merging MSAs")

    ### Align sequence on AFDB sequences - to not have missing residues 
    if full_seq !== missing
        println("Aligning MSA on full sequence provided")
        ids, seqs=read_a3m(joinpath(out_folder, "all_sequence.a3m"))

        row_query=filter!(
            row -> row.PDB == query_pdb_code && row.CHAIN == query_chain_code,
            sifts_uniprot_mapping,
        )
        res_beg=row_query[1, :SP_BEG]
        res_end=row_query[1, :SP_END]
        println("Query sequence range in UniProt: $res_beg - $res_end")
        same_sull_seq=full_seq[res_beg:res_end]
        if length(same_sull_seq) == 0
            @error "The provided full sequence has no overlap with the sequence range in UniProt. Check the sequence and the mapping."
        end

        align_seqs=align_full_seq(same_sull_seq, seqs)
        align_msa_path=joinpath(out_folder, "all_sequence_align_uniprot_seq.a3m")
        println("Writing aligned MSA to $align_msa_path")
        open(align_msa_path, "w") do io
            for (id, align_seq) in zip(ids, align_seqs)
                println(io, ">$id")
                println(io, align_seq)
            end
        end

    else
        align_msa_path=joinpath(out_folder, "all_sequence.a3m")
    end
    align_merged_msa = MIToS.MSA.read_file(align_msa_path, MIToS.MSA.A3M)
    progress_bar(prog, "Final MSA")

    println("Getting the aligned structures")
    structures = _get_aligned_structures(expanded_table)
    progress_bar(prog, "Aligned structures")
    println("Clustering structures")
    clusters, cl2msa, cl2pdb = create_template_clusters_hobohm(
        expanded_table,
        align_merged_msa,
        structures,
        cutoff,
    )
    progress_bar(prog, "Clustering Hobohm")
    println("Create folder")
    create_folder_structure_hobohm(clusters, cl2msa, cl2pdb, out_folder = out_folder)
    println("Cleaning MSA and template names for AlphaFold2 input")

    clean_msa_template_names(clusters, out_folder)
    progress_bar(prog, "Creating folders + cleanup")
    println("----------------------------------------")
    println("AlphaConformers finished running.")
    println("----------------------------------------")
end
