# Progress bar -------------------------------- #
mutable struct Progress
    steps::Vector{String}   # ← Vector{String}, pas String
    current::Int
    total::Int
end

function progress_bar(p::Progress, step_name::String)
    p.current += 1
    pct = round(Int, 100 * p.current / p.total)
    filled = round(Int, 40 * p.current / p.total)
    bar = "█" ^ filled * "░" ^ (40 - filled)
    println("\n[$(p.current)/$(p.total)] $step_name")
    println("[$bar] $pct%")
    flush(stdout)
end

# Structure distance -------------------------------- #
function _aligned_pdb_file(query, target, aligned_structures_folder)
    file_name = "aln_$(query)_$(target).pdb"
    joinpath(aligned_structures_folder, file_name)
end

function _get_aligned_residues(query, target, paths, tstart, tend)
    # msa = read(paths.msa, MIToS.MSA.FASTA)
    pdb_file = _aligned_pdb_file(query, target, paths)
    res = MIToS.PDB.read_file(pdb_file, MIToS.PDB.PDBFile)
    # NOTE: Foldseek creates a single chain for the aligned structures: A
    # NOTE: tstart and tend are the residue numbers in the Foldseek-aligned structure
    res[tstart:tend]
end

# NOTE: This function only works before adding external structures into the
# Foldseek results, as it relies on the structures generated by Foldseek.
function _get_aligned_structures(foldseek_results::DataFrames.DataFrame)
    structures = OrderedCollections.OrderedDict{String,Vector{MIToS.PDB.PDBResidue}}()
    for row in eachrow(foldseek_results)
        paths = _get_paths(row.file)
        try
            structures[row.target] = _get_aligned_residues(row.query, row.target, 
                paths.structures, row.tstart, row.tend)
        catch err
            @error "Error ($err) getting structures from row: $row"
            continue
        end
    end
    structures
end

# Sequence alignment --------------------------------------- #

function get_res_beg_end(pdb_file::String)
    res_ids = Int[]

    open(pdb_file, "r") do io
        for line in eachline(io)
            if startswith(line, "ATOM")
                raw = strip(line[23:26])

                # 👉 garder uniquement les chiffres
                num = match(r"\d+", raw)

                if num !== nothing
                    push!(res_ids, parse(Int, num.match))
                end
            end
        end
    end

    return minimum(res_ids), maximum(res_ids)
end

function vector_to_msa(seqs::Vector{String})
    names = ["seq_$(i)" for i in 1:length(seqs)]

    tmpfile = tempname() * ".fasta"

    open(tmpfile, "w") do io
        for (name, seq) in zip(names, seqs)
            println(io, ">$name")
            println(io, seq)
        end
    end

    msa = read(tmpfile, FASTA)

    return msa
end

function align_full_seq(full_seq, msa)
    
    ref_seq = msa[1]  # la première séquence de l'MSA est la référence
    @show ref_seq
    @show full_seq
    mapping = Int[]  # positions dans ref_seq ou 0 si gap

    i = 1  # index ref_seq

    for c in full_seq
        if i <= length(ref_seq) && c == ref_seq[i]
            push!(mapping, i)
            i += 1
        else
            push!(mapping, 0)  # gap
        end
    end
    @show mapping
    # Construire nouveau MSA
    new_msa = String[]

    # 1️⃣ première ligne = full_seq (ta référence propre)
    push!(new_msa, full_seq)

    # 2️⃣ autres séquences
    for seq in msa[2:end]
        seq_string=seq
        new_seq = ""
        for pos in mapping
            if pos == 0
                new_seq *= "-"
            else
                new_seq *= seq_string[pos]
            end
        end
        push!(new_msa, new_seq)
    end
    @show length(new_msa)
    return new_msa
end

"""
This module contains the main function to run the whole pipeline of AlphaConformers, from running foldseek to creating the folders for AlphaFold2 input.
Input : 
- input_pdb: the path to the query pdb file, the name of the file must be in the format "PDBCODE_CHAIN.pdb", for example "1EX6_B.pdb"
- pdb_folder: the path to the folder containing all the pdb files, this is used to create the foldseek database for the targets
- out_folder: the path to the output folder where all the results will be stored, the output folder will be created if it does not exist
- n_threads: the number of threads to use for foldseek, default is the number of available threads
- db: the path to the foldseek database to use for the search, default is "/alpha/database/pdb/fullpdb"
- evalue_cutoff: the e-value cutoff to filter the foldseek results, default is 1e-5, set to NaN to not filter
- cutoff: the RMSD cutoff to use for the structural clustering, default is 1.0
- test_analyse: if true, the function will remove the known structures of the query uniprot from the targets, this is used to test the effect of keeping or not the known structures of the query in the targets, default is false
- keep_query: if true, the function will keep the query structure in the targets after removing the known structures of the query uniprot, default is true
- full_seq: the full sequence of the query, this is used to align the MSA on the full sequence to not have missing residues, default is missing, if provided, the function will align the MSA on the full sequence and write the aligned MSA to the output folder
Output: 
- the function will create a folder for each cluster of templates, each folder will contain the aligned MSA and the pdb files of the templates in the cluster, the names of the templates in the MSA and the pdb files will be cleaned to be compatible with AlphaFold2 input

"""
#Main function to run the whole pipeline of AlphaConformers
function alphaconformers(input_pdb::String, pdb_folder::String, out_folder::String;
        n_threads::Int=Threads.nthreads(),
        db::Vector{String}=["/alpha/database/pdb/fullpdb"], 
        evalue_cutoff::Float64=1e-5,cutoff::Float64=1.0,
        test_analyse::Bool=false,keep_query::Bool=true,
        full_seq::Union{Missing,String} = missing
        )
    println("----------------------------------------")
    println("AlphaConformers start running...")
    println("----------------------------------------")

    steps = [
    "Foldseek search",
    "Merging tables",
    "Ajout conformations connues",
    "Fusion des MSAs",
    "Final MSA",
    "Structures alignées",
    "Clustering Hobohm",
    "Création dossiers + nettoyage"
    ]
    n_steps = test_analyse ? 8 : 7   # alignement conditionnel
    prog = Progress(steps, 0, n_steps)


    println("Threads disponibles",Threads.nthreads())

    #Get the query pdb code and chain from the input file name
    parts=split(basename(input_pdb), "_")
    if length(parts) < 2
        error("Le nom du fichier PDB doit être au format 'PDBCODE_CHAIN.pdb', par exemple '1EX6_B.pdb'")
    end
    query_pdb_code = parts[1]
    query_chain_code = split(parts[2],".")[1]
    println("Query PDB code: $query_pdb_code, Query chain code: $query_chain_code")

    println("Running Foldseek")
    output = run_foldseek(input_pdb, n_threads, db, out_folder=out_folder) 
    progress_bar(prog, "Foldseek search")
    # Init empty vector to store the table files
    output_vector = Vector{String}()
    for item in output
        push!(output_vector, item.table_file)  # Ajouter au vecteur
    end
    
    # Create the merged table
    merged_table = merge_tables(output_vector)
    println("Size of merged table: $(size(merged_table))")
    if !isnan(evalue_cutoff)
        println("Filtering results with e-value cutoff: $evalue_cutoff")
        filter!(row -> row.evalue < evalue_cutoff, merged_table)
        println("Size of merged table after filtering : $(size(merged_table))")
    end

    if size(merged_table, 1) == 0
        @error "No results found after filtering with e-value cutoff: $evalue_cutoff"
        return
    end
    progress_bar(prog, "Merging tables")
    println("Adding known conformations")
    
    sifts_uniprot_mapping = get_uniprot_mapping()
    clean_table = add_known_conformations!(deepcopy(merged_table), sifts_uniprot_mapping,pdb_folder,out_folder,input_pdb,n_threads)
    println("Size of all target found : $(size(clean_table))")
    progress_bar(prog, "Ajout conformations connues")

    if test_analyse 
        println("Remove know structure from query uniprot from targets (keep query itself in targets)")
        query_found=filter(row -> startswith(row.target, uppercase(query_pdb_code)) && endswith(row.target, uppercase(query_chain_code)), clean_table)
        if isempty(query_found)
            @warn "The query structure is not in all target found ! "
        end
        expanded_table=delete_query_from_target(deepcopy(clean_table),sifts_uniprot_mapping,String(query_pdb_code),String(query_chain_code))
        println("Size of after removing query other conformations: $(size(expanded_table))")
        if keep_query 
            println("Keep query in targets")
            expanded_table=vcat(query_found,expanded_table)
            println("Size of expanded table with query: $(size(expanded_table))")
        end
        isempty(expanded_table) && error("No targets remaining after removing query from targets.")
        CSV.write(joinpath(out_folder,"expanded_table_delete.csv"),expanded_table)
    else 
        expanded_table=deepcopy(clean_table)
    end
    
    println("Create merged MSAS")
    merged_msa = merge_msas(expanded_table)
    MIToS.MSA.write_file(joinpath(out_folder, "all_sequence.a3m"), merged_msa, MIToS.MSA.A3M)
    println("Size of merged MSA: $(size(merged_msa))")
    progress_bar(prog, "Fusion des MSAs")

    ### Align sequence on AFDB sequences - to not have missing residues 
    if full_seq !== missing
        println("Aligning MSA on full sequence provided")
        ids,seqs=read_a3m(joinpath(out_folder, "all_sequence.a3m"))

        row_query=filter!(row -> row.PDB == query_pdb_code && row.CHAIN == query_chain_code, sifts_uniprot_mapping)
        res_beg=row_query[1,:SP_BEG]
        res_end=row_query[1,:SP_END]
        println("Query sequence range in UniProt: $res_beg - $res_end")
        same_sull_seq=full_seq[res_beg:res_end]
        if length(same_sull_seq) == 0
            @error "The provided full sequence has no overlap with the sequence range in UniProt. Check the sequence and the mapping."
        end
        
        align_seqs=align_full_seq(same_sull_seq,seqs)
        align_msa_path=joinpath(out_folder, "all_sequence_align_uniprot_seq.a3m")
        println("Writing aligned MSA to $align_msa_path")
        open(align_msa_path, "w") do io
            for (id, align_seq) in zip(ids, align_seqs)
                    println(io, ">$id")
                    println(io, align_seq)
            end
        end
        
    else
        align_msa_path=joinpath(out_folder, "all_sequence.a3m")
    end
    align_merged_msa = MIToS.MSA.read_file(align_msa_path,MIToS.MSA.A3M)
    progress_bar(prog, "Final MSA")

    println("Getting the aligned structures")
    structures = _get_aligned_structures(expanded_table)
    progress_bar(prog, "Structures alignées")
    println("Clustering structures")
    clusters, cl2msa, cl2pdb= create_template_clusters_hobohm(expanded_table, align_merged_msa, structures,cutoff)
    progress_bar(prog, "Clustering Hobohm")
    println("Create folder")
    create_folder_structure_hobohm(clusters, cl2msa, cl2pdb, out_folder=out_folder)
    println("Cleaning MSA and template names for AlphaFold2 input")

    clean_msa_template_names(clusters,out_folder)
    progress_bar(prog, "Création dossiers + nettoyage")
    println("----------------------------------------")
    println("AlphaConformers finished running.")
    println("----------------------------------------")
end
